title: ROB 320
description: University of Michigan offering of Robotics 320 in Winter 24
theme: just-the-docs

url: https://robotoperatingsystemscourse.github.io
baseurl: '' # the subpath of your site, e.g. /blog

favicon_ico:

search_enabled: true

# Aux links for the upper right navigation
aux_links:
  Zoom: https://umich.zoom.us/j/97255605729
  Google Drive: https://drive.google.com/drive/folders/17gsqjUeFjiynJGbo9yWazmTKToilAz_z?usp=drive_link
  Piazza: https://piazza.com/umich/winter2025/rob320/home
  Autograder: https://autograder.io

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Collections for website data
collections:
  staff:

# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: staff
    values:
      layout: staff
      subpath: '/assets/images/staff/'
